spring:
  profiles:
    active: dev


---
server:
  port: 80
  servlet:
    context-path: /qujin/client
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/qujin?serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: ozg123zxc
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      async-init: true

  redis:
    host: 49.234.86.39
    port: 6379
    password: ozg123zxc


mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-conf.xml
  global-config:
    refresh-mapper: true
    cache-enabled: true





---
server:
  port: 8081
  servlet:
    context-path: /qujin/client
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/qujin?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ozg123zxc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      async-init: true
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  global-config:
    refresh-mapper: true
    cache-enabled: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true

